// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/alive/agent": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "查询记录状态",
                "tags": [
                    "Agent"
                ],
                "summary": "查询记录状态",
                "parameters": [
                    {
                        "type": "string",
                        "description": "是否快速查询 默认 false || true || quick",
                        "name": "fast",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "记录上报接口",
                "tags": [
                    "Agent"
                ],
                "summary": "记录上报接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "探活类型",
                        "name": "type",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "新增配置",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "$ref": "#/definitions/model.Record"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/alive/agent/type/{name}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "根据工具查看记录",
                "tags": [
                    "Agent"
                ],
                "summary": "根据工具查看记录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "被探活工具",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/alive/agent/{name}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "查询记录状态",
                "tags": [
                    "Agent"
                ],
                "summary": "查询记录状态",
                "parameters": [
                    {
                        "type": "string",
                        "description": "探活类型",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "是否快速查询 默认 false || true",
                        "name": "fast",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/alive/config": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获取配置",
                "tags": [
                    "Config"
                ],
                "summary": "获取配置",
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/alive/config/raw": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获取原始配置",
                "tags": [
                    "Config"
                ],
                "summary": "获取原始配置",
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "修改配置",
                "tags": [
                    "Config"
                ],
                "summary": "修改配置",
                "parameters": [
                    {
                        "description": "修改配置",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/alive/hbcheck": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "心跳检查结果",
                "tags": [
                    "Heartbeat"
                ],
                "summary": "心跳检查结果",
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/alive/hbcheck/{name}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "心跳检查结果",
                "tags": [
                    "Heartbeat"
                ],
                "summary": "心跳检查结果",
                "parameters": [
                    {
                        "type": "string",
                        "description": "主机名",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/alive/heartbeat": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "上报Agent心跳",
                "tags": [
                    "Heartbeat"
                ],
                "summary": "上报Agent心跳",
                "parameters": [
                    {
                        "description": "新增配置",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Heartbeat"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/alive/sse": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Agent数据下发",
                "tags": [
                    "Sse"
                ],
                "summary": "Agent数据下发",
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Agent数据下发",
                "tags": [
                    "Sse"
                ],
                "summary": "Agent数据下发",
                "parameters": [
                    {
                        "description": "新增配置",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.SSE"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/alive/thirdparty": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "服务端探活查询接口",
                "tags": [
                    "ThirdParty"
                ],
                "summary": "服务端探活查询接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "是否快速查询 默认 false || true",
                        "name": "fast",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/login": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "后端服务登录接口",
                "tags": [
                    "Auth"
                ],
                "summary": "本地登录接口",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Resp"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/get": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获取value，逐级数据查询",
                "tags": [
                    "admin"
                ],
                "summary": "查询指定key的值",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "查询key",
                        "name": "key",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/apis/auth/logout": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "后端服务注销接口",
                "tags": [
                    "Auth"
                ],
                "summary": "注销接口",
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/apis/gvr/list": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "后端服务登录接口",
                "tags": [
                    "Auth"
                ],
                "summary": "本地登录接口",
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "接口健康检查接口",
                "tags": [
                    "Health"
                ],
                "summary": "健康检查",
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.CpuResource": {
            "type": "object",
            "properties": {
                "idle": {
                    "type": "integer"
                },
                "iowait": {
                    "type": "integer"
                },
                "logical": {
                    "type": "integer"
                },
                "percent": {
                    "type": "number"
                },
                "physical": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "used": {
                    "type": "integer"
                }
            }
        },
        "model.DiskResource": {
            "type": "object",
            "properties": {
                "free": {
                    "type": "integer"
                },
                "fstype": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "percent": {
                    "type": "number"
                },
                "total": {
                    "type": "integer"
                },
                "used": {
                    "type": "integer"
                }
            }
        },
        "model.Heartbeat": {
            "type": "object",
            "properties": {
                "cpu": {
                    "$ref": "#/definitions/model.CpuResource"
                },
                "disk": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.DiskResource"
                    }
                },
                "diskFreeDrives": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "history": {
                    "$ref": "#/definitions/model.History"
                },
                "host": {
                    "type": "string"
                },
                "last": {
                    "type": "string"
                },
                "memory": {
                    "$ref": "#/definitions/model.Resource"
                },
                "message": {
                    "type": "string"
                },
                "port": {
                    "type": "string"
                },
                "status": {
                    "type": "boolean"
                },
                "time": {
                    "type": "string"
                }
            }
        },
        "model.History": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "success": {
                    "type": "string"
                }
            }
        },
        "model.Record": {
            "type": "object",
            "properties": {
                "checklist": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.RecordList"
                    }
                },
                "history": {
                    "$ref": "#/definitions/model.History"
                },
                "host": {
                    "type": "string"
                },
                "kind": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "status": {
                    "type": "boolean"
                },
                "time": {
                    "type": "string"
                }
            }
        },
        "model.RecordList": {
            "type": "object",
            "properties": {
                "config": {},
                "error": {
                    "type": "string"
                },
                "history": {
                    "$ref": "#/definitions/model.History"
                },
                "kind": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "result": {
                    "type": "string"
                },
                "status": {
                    "type": "boolean"
                },
                "time": {
                    "type": "string"
                }
            }
        },
        "model.Resource": {
            "type": "object",
            "properties": {
                "free": {
                    "type": "integer"
                },
                "percent": {
                    "type": "number"
                },
                "total": {
                    "type": "integer"
                },
                "used": {
                    "type": "integer"
                }
            }
        },
        "model.Resp": {
            "type": "object",
            "properties": {
                "baseType": {
                    "type": "string"
                },
                "code": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "model.SSE": {
            "type": "object",
            "properties": {
                "heartbeat": {
                    "type": "boolean"
                },
                "ip": {
                    "type": "string"
                },
                "t": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	// LeftDelim:        "{{",
	// RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
