definitions:
  model.Resp:
    properties:
      baseType:
        type: string
      code:
        type: string
      message:
        type: string
      status:
        type: integer
      type:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/admin/get:
    get:
      description: 获取value，逐级数据查询
      parameters:
      - description: token
        in: query
        name: token
        type: string
      - description: 查询key
        in: query
        name: key
        required: true
        type: string
      responses:
        "200":
          description: success
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 查询指定key的值
      tags:
      - admin
  /apis/auth/login/local:
    post:
      description: 后端服务登录接口
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Resp'
      security:
      - ApiKeyAuth: []
      summary: 本地登录接口
      tags:
      - Auth
  /apis/auth/logout:
    post:
      description: 后端服务注销接口
      responses:
        "200":
          description: success
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 注销接口
      tags:
      - Auth
  /apis/gvr/list:
    post:
      description: 后端服务登录接口
      responses:
        "200":
          description: success
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 本地登录接口
      tags:
      - Auth
  /health:
    get:
      description: 接口健康检查接口
      responses:
        "200":
          description: success
          schema:
            type: string
      summary: 健康检查
      tags:
      - Health
swagger: "2.0"
